version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development  # Certifique-se de que está configurado para o target correto
    container_name: nestjs_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network
    restart: unless-stopped

  db:
  image: mysql:8.0
  container_name: mysql_db
  env_file:
    - .env
  ports:
    - "3306:3306"
  volumes:
    - db_data:/var/lib/mysql:delegated
  networks:
    - my_network
  restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  my_network:
    driver: bridge
