version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: irede-produtos-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_USERNAME: lobo
      DATABASE_PASSWORD: Nhaca70x07@
      DATABASE_NAME: irede_produtos
      JWT_SECRET: nhaca
      JWT_EXPIRATION: 60m
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network

  database:
    image: mysql:8
    container_name: irede-produtos-db
    environment:
      MYSQL_ROOT_PASSWORD: Nhaca70x07@
      MYSQL_DATABASE: irede_produtos
      MYSQL_USER: lobo
      MYSQL_PASSWORD: Nhaca70x07@
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
