

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_TYPE=mysql
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=lobo
      - DATABASE_PASSWORD=Nhaca70x07@
      - DATABASE_NAME=irede
      - JWT_SECRET=nhaca
      - JWT_EXPIRATION=60m
    depends_on:
      - database
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: irede
      MYSQL_USER: lobo
      MYSQL_PASSWORD: Nhaca70x07@
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
